### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by Anitouch** [skkuull/h1-mod#124]
How to change language?

**Comment by V3nilla** [comment]
> Soon™.
> 
> ![image](https://user-images.githubusercontent.com/7479947/176173841-783c102b-d7d3-4453-969c-1a75af6e7a2f.png)
> 
> I just need language packs to test it out, if you have it, please ping **Arwent#0001** on Discord.

I have russian language pack with DLC's, but you discord isnt working(Arwent#0001 is not accepting friend requests)
